- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        cpu:
          limits: 100m
          requests: 25m
        image:
          Name: lsheiba/tensorflow-jupyter
          Tag: null
        memory:
          limits: 2048Mi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 1Gi
        replicas: 1
        serviceType: LoadBalancer
    name: tensorflow-1
    src: https://github.com/lsheiba/tfj-v1/
    version: 1.0.2
  name: tf2
