- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        Component: demo-server
        CpuLimits: 200m
        CpuRequests: 25m
        Image:
          kuberlab.io/image:
            CandidateTag: '*'
            Name: kuberlab/demo-web-server
        MemoryLimits: 64Mi
        MemoryRequests: 64Mi
        Name: demo
        Replicas: 1
        ServerVersion: 1.2.0
    name: demo-web-server
    order: null
    src: https://github.com/kuberlab/demo-web-server/Chart
    version: '*'
  name: kuberlab
- charts:
  - clusters:
    - demo-cluster-1
    configuration: {}
    name: wordpress
    order: null
    src: https://dev.kuberlab.io/kuberlab/wordpress
    version: '*'
  name: wordpress
