- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        Component: tensorflow-inception
        ContainerPort: 9090
        Image: quay.io/lachie83/inception_serving
        ImagePullPolicy: IfNotPresent
        ImageTag: latest
        Replicas: 1
        Resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ServicePort: 9090
        ServiceType: LoadBalancer
    name: tensorflow-inception
    src: https://github.com/lsheiba/charts/incubator/tensorflow-inception
    version: 0.1.1
  name: tensorflow
- charts:
  - clusters:
    - demo-cluster-1
    configuration:
      values:
        image: bitnami/wordpress:4.7-r0
        imagePullPolicy: IfNotPresent
        mariadb:
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 8Gi
        persistence:
          apache:
            accessMode: ReadWriteOnce
            size: 1Gi
          enabled: true
          wordpress:
            accessMode: ReadWriteOnce
            size: 8Gi
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        serviceType: LoadBalancer
        wordpressBlogName: User's Blog!
        wordpressEmail: user@example.com
        wordpressFirstName: FirstName
        wordpressLastName: LastName
        wordpressUsername: user
    name: wordpress
    src: https://github.com/lsheiba/wordpress-chart/
    version: 0.4.0
  name: wordpress
